export const gruntCatchphrasesOld = [
    'Go, my super bug Pokémon!',
    'Wherever there is light, there is also shadow.',
    'ROAR! ...How\'d that sound?',
    'Get ready to be shocked!',
    'Check out my cute Pokémon!',
    'This buff physique isn\'t just for show!',
    'Do you know how hot Pokémon fire breath can get?',
    'Battle against my Flying-type Pokémon!',
    'Ke... ke... ke... ke... ke... ke!',
    'Don\'t tangle with us!',
    'You\'ll be defeated into the ground!',
    'You\'re gonna be frozen in your tracks.',
    'Normal does not mean weak',
    'Coiled and ready to strike!',
    'Are you scared of psychics that use unseen power?',
    'Let\'s rock and roll!',
    'You\'re no match for my iron will!',
    'These waters are treacherous!'
  ] as const

  export const gruntCatchphrases = {
      'bug': 'Go, my super bug Pokémon!',
      'dark': 'Wherever there is light, there is also shadow.',
      'dragon': 'ROAR! ...How\'d that sound?',
      'electric': 'Get ready to be shocked!',
      'fairy': 'Check out my cute Pokémon!',
      'fighting': 'This buff physique isn\'t just for show!',
      'fire': 'Do you know how hot Pokémon fire breath can get?',
      'flying': 'Battle against my Flying-type Pokémon!',
      'ghost': 'Ke... ke... ke... ke... ke... ke!',
      'grass': 'Don\'t tangle with us!',
      'ground': 'You\'ll be defeated into the ground!',
      'ice': 'You\'re gonna be frozen in your tracks.',
      'normal': 'Normal does not mean weak',
      'poison': 'Coiled and ready to strike!',
      'psychic': 'Are you scared of psychics that use unseen power?',
      'rock': 'Let\'s rock and roll!',
      'steel': 'You\'re no match for my iron will!',
      'water': 'These waters are treacherous!'
  }