name: Main

on:
  push:
    branches:
      - main

jobs:
  create-release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      hasChangesets: ${{ steps.changesets.outputs.hasChangesets }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.POKEMON_GO_CHANGESETS_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.POKEMON_GO_CHANGESETS_TOKEN }}

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    name: Update Website
    uses: ./.github/workflows/deploy.yml
    needs: create-release
    if: needs.create-release.outputs.hasChangesets == 'true'
    with:
      ref: ${{ github.ref }}
