name: Update pokemon informatin

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 5" # Every Friday at 00:00

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Download pokedex info
        run: npm run pokedex:download

      - name: Generate code
        run: npm run pokedex:generate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update pokemon information
          title: Update pokemon information
          body: Update pokemon information
          branch: update-pokemon-information
          base: main
